### ISSUE TITLE
Support NuGetPackagesV2 APIs

### ISSUE THREAD

**Issue by EbenZhang** [lvermeulen/ProGet.Net#45]
I have found the NuGetPackages_GetPackages returns empty result when using ProGet 5.0.10, whereas the V2 API works fine, is there a plan to support the V2 APIs?

**Comment by lvermeulen** [comment]
I'm not sure what you mean. What is the V2 API, and what doesn't work exactly?

**Comment by EbenZhang** [comment]
there are two endpoints NuGetPackages_GetPackages and NuGetPackagesV2_GetPackages, the one this library is using is the NuGetPackages_GetPackages which returns empty result even if there are packages in the feed .

**Comment by lvermeulen** [comment]
Do you have a link to docs for NuGetPackagesV2_GetPackages?

**Comment by EbenZhang** [comment]
install the latest proget , navigate to http//youserver/reference/api , and search for the v2 api.

**Comment by lvermeulen** [comment]
Got it, will get to work on it.

**Comment by lvermeulen** [comment]
Ready for testing in [Release 1.1.0](https://github.com/lvermeulen/ProGet.Net/releases/tag/1.1.0-alpha)
